### ISSUE TITLE
Unable to run Swagger UI

### ISSUE THREAD

**Issue by kalnikh** [InseeFr/Eno-WS#4]
Hello,

We have deployed Eno-WS here in Eurostat. The web service is working as expected. However, Swagger UI is not working.  It fails with the following error:

{"status":404,"message":"Not Found","details":"No JAX-RS resource found for this path"}

We have adapted properties file with host name and port where service is running. 
We observed that basepath was "/api" and thought that it needed to be "<context-path>/api". So we changed it in SwaggerConfig and tried to make a build. There we faced some issues while building and deploying service.
1.	Pom.xml was referring to a blacklisted maven repo. This was causing some issues. 
2.	After removing this, it needed another library file (eno-jar) for which there was no jar available in the repo, so I cloned Eno project sources and build that project. 
3.	After build was successful, at deployment time Tomcat complained that spring applicationcontxt was not available. I am not sure why it was not included as part of the build. So, I manually added spring applicationContext file in the WAR file and then service could be deployed successfully. 
4.	Unfortunately we still get the same error :"No JAX-RS resource found for this path"

We have tested this service on tomcat version is "8.0.28" and "8.5.8". 
Can you please look into this and inform us how we can get swagger UI working?

Thank you in Advance.
 
Best Regards,
Nikhil Kale

**Comment by bwerquin** [comment]
Hi Nikhil Kale,

Sorry for the delay,

1 - The repository at http://download.java.net/maven/2 is deprecated, and has been replaced with https://maven.java.net/content/groups/public/
Pom.xml updated.
2 - We have to provide the eno-jar by maven central, working in progress...
3 - Fixed
4 - Fixed

I publish a new release with swagger ui operationnal.
Thanks,

Best Regards,
Benoit Werquin

**Comment by kalnikh** [comment]
Thank you for the fix. Issue will be closed.
