### ISSUE TITLE
Working of Eno Service

### ISSUE THREAD

**Issue by kalnikh** [InseeFr/Eno-WS#5]
Hello, 

We are having some issues when we are sending ddi request to the Eno service on TomEE on Linux platform. It seems that file that gets generated after first transformation, is not getting created and as a result, when that file is referred we are seeing NullPointerException,  Please see the attached logs for your reference. 
[ddi-to-xform_error.txt](https://github.com/InseeFr/Eno-WS/files/1766903/ddi-to-xform_error.txt)

We are not seeing this behaviour in Windows or on Tomcat. Are you aware of any such issue with TomEE and/or on Linux platform. 

We are seeing exactly same error for pogues xml. I have attached the logs. 
[Pogues_xml_to_ddi_error.txt](https://github.com/InseeFr/Eno-WS/files/1766905/Pogues_xml_to_ddi_error.txt)
However, this issue is seen on both windows and Linux platform .

Can you please have a look at the logs and guide us what could be going wrong here? 
Thank you, 

Best Regards,
Nikhil

**Comment by bwerquin** [comment]
Hi Nikhil,

I have never used TomEE but this online endpoint works with linux platform (Tomcat on Debian) : 
http://pogues.scfe.eu/rmspogfo/swagger-ui/dist/#/Pogues_Transforms/ddi2XForm
Can you try it ?
Please see the attached ddi example file : 
[ddi.txt](https://github.com/InseeFr/Eno-WS/files/1789229/ddi.txt)

To my mind, this is a write access folder pb.

Benoit.

**Comment by kalnikh** [comment]
Hi Benoit,

Thanks for the information. I tried using the online endpoint and it is indeed working for both ddi2xform and also for pogues-xml2ddi 

Can you please tell me what exactly is the difference between the eno-ws service and the Pogues back-office service ? To me, it seems that the functionality provided by Eno-ws is already available in Pogues? 

Can you please also inform me if the service behind the provided URL is planned as a permanent service or is only available now for tests? 

Best Regards,
Nikhil

**Comment by bwerquin** [comment]
Hi Nikhil,

You right, there is no difference between the eno-ws service and the eno endpoint on Pogues-Back-Office.
Eno-ws is just a stand alone Eno endpoint.

pogues.scfe.eu/rmspogfo is a demo version,  i ask to Franck if this provided URL will permanent (i d'on't know).

Cheer,
Benoit.

**Comment by kalnikh** [comment]
Hi Benoit,

Thanks for the information. 
However, Pogues to DDI  transformation is failing also on Tomcat(in windows and Linux both) with the error attached below. Can you please have a look? Is this something that can be fixed? 

[Pogues_xml_to_ddi_error.txt](https://github.com/InseeFr/Eno-WS/files/1819420/Pogues_xml_to_ddi_error.txt)

Thank you in advance.

Best Regards,
Nikhil Kale

**Comment by bwerquin** [comment]
Hi Nikhil,

I'm not sure to understand, there is not yet endpoint for this transformation (pogues-xml2ddi) on Eno-WS.

This is an CLI usage of Eno with Java ?
Can you give me your XML Pogues file to test it ?

Regards,
Benoit.

**Comment by kalnikh** [comment]
Hi Benoit,

OK, I did not know about this. I saw the pogues XML in eno-core project and was under impression that it is supported in eno web service. 

Please find attached the XML Pogues file that I was testing.

Best Regards,
Nikhil

[poguest.zip](https://github.com/InseeFr/Eno-WS/files/1842640/poguest.zip)

**Comment by kalnikh** [comment]
Hi Benoit,

Did you get any feedback from Franck if "pogues.scfe.eu/rmspogfo" URL will permanent?

Thanks & Best Regards,
Nikhil

**Comment by bwerquin** [comment]
Hi Nikhil,

It depends of EESNet SCFE 2...

Best regards
Benoit.
